name: Pipeline
on:
  push:
    branches: [ main ]
    tags:
     - v[12].[0-9]+.[0-9]+
    paths-ignore:
      - '.github/**'
      - README.md
jobs:
  push-main-pipeline:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.9"
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run tests
        run: uv run python -m pytest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Set Docker image tag
        run: |
          if [[ ${{ github.ref_type }} == 'tag' ]]; then
            echo "TAG_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            SHA_SHORT=$(echo "${{ github.sha }}" | cut -c 1-10)
            TIMESTAMP=$(date +%s)
            echo "TAG_NAME=$SHA_SHORT-$TIMESTAMP" >> $GITHUB_ENV
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ env.TAG_NAME }}

      - name: Update GitOps repository
        shell: bash
        env:
          GIT_TOKEN: ${{ secrets.GITOPS_PAT }}
        run: |
          # Configure git credential store
          git config --global credential.helper store
          echo "https://${GIT_TOKEN}:x-oauth-basic@github.com" > ~/.git-credentials
          
          # Remove any existing gitops directory
          rm -rf devops-stuff-k8s
          
          # Clone repository using HTTPS URL without token
          git clone https://github.com/aldredb/devops-stuff-k8s.git devops-stuff-k8s
          cd devops-stuff-k8s

          yq eval -i '.spec.template.spec.containers[0].image = "ghcr.io/${{ github.repository }}:${{ env.TAG_NAME }}"' demo-app/rollout.yaml
          
          # Commit changes
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add demo-app/rollout.yaml
          git commit -m "Update image to ${{ github.sha }}"
          
          # Push
          git push -f https://${GIT_TOKEN}@github.com//aldredb/devops-stuff-k8s.git main